"""Generate floor_day4.py from the day-3 job (floor_day3.py v2) by exact-match replacements, as floor_day2.py was
generated from day 1's: each replacement must match exactly once, and everything not replaced is day 3's, byte for
byte. The day-4 parts (PREREG amendment 3): the header and version; the inputs
(day4/windows_day4.json pinned beside the pins day 3 keeps; both arms' renders, their shapes and level-0 scales
checked); the arm-B resampler and its self-tests; the target and sham jobs per arm (arm A as day 3; arm B at core_b and
box_b, 554 px cores, sigma 52 px, the donor-frame arrays resampled to 8.64 um); the scale references; the whole
surfaces of both arms (FL_LIMIT_WHOLE for the smoke); the kept-map crop per arm; and the readout per arm plus the
difference between arms.

One detail of the profile check that amendment 3 names differs from day 3's: each target's and sham's 28-layer profile
is checked on the render's uint8
values, as the pick computed it (an exact comparison), where day 3 averaged a float32 copy, which can differ by up to
about 1e-5 grey levels and so, rarely, round to the other side of a 0.05 boundary.

  python3 make_day4.py           (writes floor_day4.py beside this file and prints how many lines changed)
  python3 make_day4.py --check   (writes nothing; exit 1 unless floor_day4.py is exactly what this generates)
"""
import difflib, hashlib, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = open(f"{HERE}/floor_day3.py").read()
REPS = [
# 1. what this job is
(r'''"""Ink detection floor, day 3 on Kaggle (PREREG.md, amendment 1): the floor on PHerc0846B's surfaces.

Built from the day-1 kernel (floor_kernel.py v5) by replacing only the day-3 parts: the inputs, the target and sham
jobs, the whole-surface jobs and the readout. Planting, scoring, inference and environment handling are day 1's,
byte for byte.

Inputs: the day-1 dataset (windows.json, masks.npz, villa_vesuvius_src.tar), day-1's own results.json (for the
reference control), day3/windows_day3.json (prep_day3.py) and the seven PHerc0846B renders (villa's vc_render_tifxyz,
31 planes; planes [1, 29) are the 28-layer volume, surface at layer 14).

Jobs: the six day-1 references again (the control); for each day-3 target, clean, the swap plant at three strengths
and two shams at each, one of PHerc0846B papyrus and one of PHerc0139 papyrus (surface to surface, no depth shift); and each whole surface, for the models' own output.
env: FL_INPUT FL_WORK FL_TMP FL_PIP FL_STRENGTHS FL_SELFTEST_ONLY FL_LIMIT_TARGETS FL_NO_INFER
"""
''', r'''"""Ink detection floor, day 4 on Kaggle (PREREG.md, amendment 3): the floor on PHerc0483B's surfaces, in two arms.

Generated from the day-3 job (floor_day3.py v2) by make_day4.py, through exact-match replacements of the day-4 parts
only: the inputs, the arm-B resampler and its self-tests, the target and sham jobs of each arm, the scale references,
the whole-surface jobs, the kept-map crop and the readout. Planting, the AUC, inference and environment handling are
day 1's, byte for byte, as on day 3.

Inputs: the day-1 dataset (windows.json, masks.npz, villa_vesuvius_src.tar), day-1's own results.json (for the
reference control), day4/windows_day4.json (prep_day4.py) and the ten PHerc0483B renders (villa's vc_render_tifxyz,
31 planes; planes [1, 29) are the 28-layer volume, surface at layer 14): arm A at 9.362 um (2806 px) and arm B at the
scan's own 8.64 um (3040 px), five surfaces each.

Jobs: the six day-1 references again (the control, for both arms); for each day-4 target in each arm, clean, the swap
plant at three strengths and two shams at each, one of PHerc0483B papyrus and one of PHerc0139 papyrus (surface to
surface, no depth shift): arm A as day 3 (512 px cores, sigma 48 px), arm B at the window's core_b and box_b (554 px
cores, sigma 52 px) with the donor-frame arrays resampled to 8.64 um; the six day-1 donor windows resampled whole to
8.64 um (the scale references, arm B, not a gate); and each whole surface of both arms, for the models' own output.
env: FL_INPUT FL_WORK FL_TMP FL_PIP FL_STRENGTHS FL_SELFTEST_ONLY FL_LIMIT_TARGETS FL_LIMIT_WHOLE FL_NO_INFER
"""
'''),
(r'''SCRIPT_VERSION = "floor_day3 v2 (24 Sep 2026): the floor on PHerc0846B (PREREG amendment 1), built from floor_kernel v5; review 4: PHerc0139 shams, inputs pinned, profiles checked"
''', r'''SCRIPT_VERSION = "floor_day4 v1 (25 Sep 2026): the floor on PHerc0483B in two arms, A at 9.362 um (primary) and B at 8.64 um (PREREG amendment 3), generated by make_day4.py from floor_day3 v2 (24 Sep 2026)"
'''),
(r'''LIMIT_TARGETS = int(os.environ.get("FL_LIMIT_TARGETS", "0"))
''', r'''LIMIT_TARGETS = int(os.environ.get("FL_LIMIT_TARGETS", "0"))
LIMIT_WHOLE = int(os.environ.get("FL_LIMIT_WHOLE", "0"))          # smoke: the first n whole surfaces of each arm
'''),
# 2. the two arms (amendment 3): every length the rules give in pixels kept at its physical size in arm B
(r'''SIGMA, DILATE, FEATHER, CORE = 48.0, 3, 2.0, 512
''', r'''SIGMA, DILATE, FEATHER, CORE = 48.0, 3, 2.0, 512
R_B = 8.64 / 9.362                  # amendment 3: one arm-B pixel (8.64 um) is R_B arm-A pixels (9.362 um)
ARMS = {"a": {"um": 9.362, "canvas": 2806, "core": 512, "sigma": 48.0},   # arm A (primary): day 3's lengths
        "b": {"um": 8.64, "canvas": 3040, "core": 554, "sigma": 52.0}}    # arm B: the same lengths at 8.64 um
'''),
(r'''           "status": "running", "errors": {}, "jobs": {}}
''', r'''           "arms": ARMS, "arm_b_ratio": R_B, "status": "running", "errors": {}, "jobs": {}}
'''),
(r'''def background(v, weight):
    """Per-layer normalised Gaussian smoothing of v (Z, H, W) with 2-D weights (H, W) in [0, 1]."""
    w = weight.astype(np.float32)
    den = ndimage.gaussian_filter(w, SIGMA)
    out = np.empty(v.shape, np.float32)
    for z in range(v.shape[0]):
        out[z] = ndimage.gaussian_filter(v[z].astype(np.float32) * w, SIGMA) / np.maximum(den, 1e-6)
''', r'''def background(v, weight, sigma=SIGMA):
    """Per-layer normalised Gaussian smoothing of v (Z, H, W) with 2-D weights (H, W) in [0, 1]."""
    w = weight.astype(np.float32)
    den = ndimage.gaussian_filter(w, sigma)
    out = np.empty(v.shape, np.float32)
    for z in range(v.shape[0]):
        out[z] = ndimage.gaussian_filter(v[z].astype(np.float32) * w, sigma) / np.maximum(den, 1e-6)
'''),
# 3. the resampler to 8.64 um, and its self-test, run with day 3's before anything is read
(r'''selftest()
if SELFTEST_ONLY:
''', r'''def to_b(a, linear, n_out=554):
    """Amendment 3: a donor-frame array at 9.362 um (28 x n x n or n x n; n = 512 for a core, 1024 for a window)
    resampled to 8.64 um. Output voxel (z, y, x) takes the input's value at (14 + (z - 14) R_B, c + (y - c_out) R_B,
    c + (x - c_out) R_B), c = (n - 1) / 2, c_out = (n_out - 1) / 2: a 28 x 554 x 554 arm-B core reads the 28 x 512 x 512
    donor core (a 1109 px window the 1024 px one), always inside it. Linear for the residuals and M_soft; nearest
    neighbour for M and N, which stay binary."""
    a = np.asarray(a)
    n = a.shape[-1]
    if a.ndim not in (2, 3) or a.shape[-2] != n or (a.ndim == 3 and a.shape[0] != 28):
        raise ValueError(f"to_b: shape {a.shape}")
    kw = dict(offset=([14.0 - 14.0 * R_B] if a.ndim == 3 else []) + [(n - 1) / 2.0 - (n_out - 1) / 2.0 * R_B] * 2,
              output_shape=a.shape[:-2] + (n_out, n_out), mode="nearest")
    if linear:
        return ndimage.affine_transform(a.astype(np.float32), [R_B] * a.ndim, order=1, **kw)
    return ndimage.affine_transform(a.astype(np.uint8), [R_B] * a.ndim, order=0, **kw).astype(bool)


def selftest_resample():
    """Code, not science (amendment 3): a flat field stays flat; a disc keeps its physical area within 1 %; a ramp along
    each axis comes out as to_b's map, so the centre goes to the centre and every mapped point lies inside the donor
    core (and window); masks stay binary, each voxel the nearest input voxel's, and ink and background stay apart."""
    flat = to_b(np.full((28, 512, 512), 100, np.float32), True)
    ok_flat = bool(flat.shape == (28, 554, 554) and np.abs(flat - 100).max() < 1e-3
                   and to_b(np.ones((512, 512), bool), False).all())
    yy, xx = np.mgrid[0:512, 0:512]
    area = {}
    for tag_, (cy, cx, rad) in {"centred_r100": (255.5, 255.5, 100.0), "off_centre_r40": (130.2, 371.7, 40.0)}.items():
        disc = (yy - cy) ** 2 + (xx - cx) ** 2 < rad * rad
        area[tag_] = [round(float(to_b(disc, False).sum() * 8.64 ** 2 / (disc.sum() * 9.362 ** 2)), 4),
                      round(float(to_b(soft(disc), True).sum() * 8.64 ** 2 / (soft(disc).sum() * 9.362 ** 2)), 4)]
    ok_area = all(abs(x - 1) < 0.01 for v_ in area.values() for x in v_)
    want_z = 14 + (np.arange(28) - 14) * R_B
    want_yx = 255.5 + (np.arange(554) - 276.5) * R_B
    want_w = 511.5 + (np.arange(1109) - 554.0) * R_B
    rz = to_b(np.broadcast_to(np.arange(28, dtype=np.float32)[:, None, None], (28, 512, 512)), True)
    ry = to_b(np.broadcast_to(np.arange(512, dtype=np.float32)[None, :, None], (28, 512, 512)), True)
    rx = to_b(np.broadcast_to(np.arange(512, dtype=np.float32)[None, None, :], (28, 512, 512)), True)
    rw = to_b(np.broadcast_to(np.arange(1024, dtype=np.float32)[:, None], (1024, 1024)), True, 1109)
    err = [float(np.abs(rz - want_z[:, None, None]).max()), float(np.abs(ry - want_yx[None, :, None]).max()),
           float(np.abs(rx - want_yx[None, None, :]).max()), float(np.abs(rw - want_w[:, None]).max())]
    centre = [float(rz[14, 0, 0]), float((ry[0, 276, 0] + ry[0, 277, 0]) / 2), float(rw[554, 0])]
    span = {"z": [float(rz.min()), float(rz.max())], "core": [float(ry.min()), float(ry.max())],
            "window": [float(rw.min()), float(rw.max())]}
    ok_map = bool(max(err) < 1e-3 and abs(centre[0] - 14) < 1e-3 and abs(centre[1] - 255.5) < 1e-3
                  and abs(centre[2] - 511.5) < 1e-3 and span["z"][0] >= 0 and span["z"][1] <= 27
                  and span["core"][0] >= 0 and span["core"][1] <= 511 and span["window"][0] >= 0
                  and span["window"][1] <= 1023)
    m = np.random.default_rng(1).random((512, 512)) < 0.3
    near = np.rint(want_yx).astype(int)
    ink = (yy - 255.5) ** 2 + (xx - 255.5) ** 2 < 60.0 ** 2
    bgm = ~ndimage.binary_dilation(ink, iterations=DILATE)
    ok_mask = bool(to_b(m, False).dtype == bool and np.array_equal(to_b(m, False), m[np.ix_(near, near)])
                   and not (to_b(ink, False) & to_b(bgm, False)).any())
    RESULTS["selftest_resample"] = {"flat": ok_flat, "physical_area_ratio_nearest_linear": area, "map_max_error": err,
                                    "centre_maps_to": centre, "mapped_span": span, "masks_binary_nearest_apart": ok_mask,
                                    "pass": bool(ok_flat and ok_area and ok_map and ok_mask)}
    save()
    log(f"resampler self-test: flat {ok_flat}, area {area}, map error {max(err):.1e}, centre {centre}, span {span}, "
        f"masks {ok_mask}")
    if not RESULTS["selftest_resample"]["pass"]:
        RESULTS["status"] = "failed: resampler self-test"
        save()
        raise SystemExit("resampler self-test failed")


selftest()
selftest_resample()
if SELFTEST_ONLY:
'''),
# 4. inputs: the day-4 windows (pinned) and both arms' renders, each checked by its own metadata
(r'''w3 = sorted(glob.glob(f"{ROOT}/**/windows_day3.json", recursive=True))
if not w3:
    raise SystemExit(f"no windows_day3.json under {ROOT}")
W3 = json.load(open(w3[0]))
if W3.get("day") != 3 or W3.get("version") != 3:
    raise SystemExit("windows_day3.json is not day 3, version 3")
''', r'''w4 = sorted(glob.glob(f"{ROOT}/**/windows_day4.json", recursive=True))
if not w4:
    raise SystemExit(f"no windows_day4.json under {ROOT}")
W4 = json.load(open(w4[0]))
if W4.get("day") != 4 or W4.get("version") != 4:
    raise SystemExit("windows_day4.json is not day 4, version 4")
for rec in W4["targets"] + W4["shams"]:                               # each window's core and box in both arms
    for arm, sfx, n_box in (("a", "", 1024), ("b", "_b", 1109)):
        (c0, c1, c2, c3), (b0, b1, b2, b3) = rec["core" + sfx], rec["box" + sfx]
        if not (c1 - c0 == c3 - c2 == ARMS[arm]["core"] and b1 - b0 == b3 - b2 == n_box and 0 <= b0 <= c0 and c1 <= b1
                and 0 <= b2 <= c2 and c3 <= b3 and b1 <= ARMS[arm]["canvas"] and b3 <= ARMS[arm]["canvas"]):
            raise SystemExit(f"windows_day4.json: {rec['surface']} core{sfx} {rec['core' + sfx]} in box{sfx} "
                             f"{rec['box' + sfx]} is not a {ARMS[arm]['core']} px core in a {n_box} px window")
'''),
(r'''RENDERS = {}
for p in sorted(glob.glob(f"{ROOT}/**/render_segment_given.zarr", recursive=True)):
    m = re.search(r"pherc0846b-render-(s\d\d|1)\b", p)
    if m:
        RENDERS["s01" if m.group(1) == "1" else m.group(1)] = zarr.open(f"{p}/0", mode="r")
if sorted(RENDERS) != sorted(W3["surfaces"]):
    raise SystemExit(f"renders {sorted(RENDERS)} do not match the day-3 windows' surfaces {sorted(W3['surfaces'])}")
RESULTS["inputs"]["sha256"]["windows_day3.json"] = sha256(w3[0])
RESULTS["inputs"]["sha256"]["day1_results.json"] = sha256(day1[0])
RESULTS["inputs"]["renders"] = {s: list(a.shape) for s, a in RENDERS.items()}
PINNED = {"windows.json": "c3e90e83effc8f4adc61b44bb1b8bbda0425605031fa24d7401d300baa9e0828",   # amendment 1: the
          "masks.npz": "f87c5cf97f01fb545fb20171c51afe2ca90f1fc7dd3d493086ca93068249189c",      # inputs, pinned
          "windows_day3.json": "278eae907664a5e2f44ff8ab282c33adb34b0521280d24eb43373f6bf70317b0",
          "day1_results.json": "61f6af77bc64189f5442cb9ee56461ffb618a48d2a5191662f7c76d7ee2e2056"}
''', r'''RENDERS = {"a": {}, "b": {}}                                          # amendment 3: both arms of each surface
RESULTS["inputs"]["renders"] = {"a": {}, "b": {}}
for p in sorted(glob.glob(f"{ROOT}/**/render_segment_given.zarr", recursive=True)):
    m = re.search(r"pherc0483b-render-(a|b)-(s\d\d)\b", p)
    if m:
        arm, sid = m.group(1), m.group(2)
        ms = zarr.open_group(p, mode="r").attrs.asdict().get("multiscales") or [{}]
        sc = [[float(x) for x in t_["scale"]] for d_ in ms[0].get("datasets", []) if str(d_.get("path")) == "0"
              for t_ in d_.get("coordinateTransformations", []) if t_.get("type") == "scale"]
        arr = zarr.open(f"{p}/0", mode="r")
        if sid in RENDERS[arm] or tuple(arr.shape) != (31, ARMS[arm]["canvas"], ARMS[arm]["canvas"]) or len(sc) != 1 \
                or max(abs(x - ARMS[arm]["um"]) for x in sc[0]) > 0.001:
            RESULTS["status"] = (f"failed: render {arm} {sid} ({p}): found twice, or shape {tuple(arr.shape)} or level-0 "
                                 f"scale {sc} is not the arm's (31 x {ARMS[arm]['canvas']} px, {ARMS[arm]['um']} um)")
            save()
            raise SystemExit(RESULTS["status"])
        RENDERS[arm][sid] = arr
        RESULTS["inputs"]["renders"][arm][sid] = {"shape": list(arr.shape), "scale_um": sc[0]}
for arm in ARMS:
    if sorted(RENDERS[arm]) != sorted(W4["surfaces"][arm]):
        raise SystemExit(f"arm {arm}: {len(RENDERS[arm])} renders {sorted(RENDERS[arm])} do not match the "
                         f"{len(W4['surfaces'][arm])} surfaces of the day-4 windows {sorted(W4['surfaces'][arm])}")
RESULTS["inputs"]["sha256"]["windows_day4.json"] = sha256(w4[0])
RESULTS["inputs"]["sha256"]["day1_results.json"] = sha256(day1[0])
PINNED = {"windows.json": "c3e90e83effc8f4adc61b44bb1b8bbda0425605031fa24d7401d300baa9e0828",   # amendment 1: the
          "masks.npz": "f87c5cf97f01fb545fb20171c51afe2ca90f1fc7dd3d493086ca93068249189c",      # inputs, pinned
          "windows_day4.json": "6d19cf5b871b3ed455f396d8d7ea9facdc71a60eeaf91c394b81d93818e9ac5e",  # amendment 3
          "day1_results.json": "61f6af77bc64189f5442cb9ee56461ffb618a48d2a5191662f7c76d7ee2e2056"}
'''),
# 5. the jobs: each job's own voxel size and core; the donors at 8.64 um and the scale references
(r'''SCORE = {}                     # job -> (positives, negatives, (y0, x0)) on the 1024 px window; maps kept for the core
''', r'''SCORE = {}                     # job -> (positives, negatives, (y0, x0, core px)) on its window; maps kept for the core
'''),
(r'''def write_job(name, vol28):
    path = f"{jobs_dir}/{name}/surface-volume.zarr"
    data = np.ascontiguousarray(vol28[LAYERS[0]:LAYERS[1]])
    g = zarr.open_group(path, mode="w", zarr_format=2)
    g.attrs.update({"floor": name, "layers": list(LAYERS), "voxel_um": 9.362})
''', r'''def write_job(name, vol28, voxel_um=9.362):
    path = f"{jobs_dir}/{name}/surface-volume.zarr"
    data = np.ascontiguousarray(vol28[LAYERS[0]:LAYERS[1]])
    g = zarr.open_group(path, mode="w", zarr_format=2)
    g.attrs.update({"floor": name, "layers": list(LAYERS), "voxel_um": voxel_um})
'''),
(r'''def core_offset(rec):
    return rec["core"][0] - rec["box"][0], rec["core"][2] - rec["box"][2]
''', r'''def core_offset(rec, sfx=""):
    return rec["core" + sfx][0] - rec["box" + sfx][0], rec["core" + sfx][2] - rec["box" + sfx][2]
'''),
(r'''donors = []
''', r'''donors, donors_b = [], []                                            # arm A (day 3's) and arm B (at 8.64 um)
'''),
(r'''    SCORE[name] = (pos_w, neg_w, (oy, ox))
''', r'''    SCORE[name] = (pos_w, neg_w, (oy, ox, CORE))
'''),
(r'''                                             "ink_contrast_at_sheet": round(prof[d["sheet_layer"]], 3)})
save()
log(f"{len(donors)} donors read; references written")
''', r'''                                             "ink_contrast_at_sheet": round(prof[d["sheet_layer"]], 3)})
    # amendment 3, arm B: M and N by nearest neighbour, the residual and M_soft linearly, all at 8.64 um; k's
    # denominator on the resampled residual; and the whole donor window at 8.64 um, masks carried: a scale reference
    if box.shape != (28, 1024, 1024):
        raise SystemExit(f"donor {i}: window {box.shape}, not 28 x 1024 x 1024")
    ink_b, neg_b, resid_b = to_b(ink, False), to_b(neg, False), to_b(resid, True)
    k_den_b = rstd(resid_b[LAYERS[0]:LAYERS[1]][:, neg_b])
    prof_b = [float(resid_b[z][ink_b].mean() - resid_b[z][neg_b].mean()) / max(k_den_b, 1e-6) for z in range(28)]
    sheet_b = int(round(14 + (d["sheet_layer"] - 14) / R_B))          # the arm-B layer at the sheet's depth
    area_b = float(ink_b.sum() * ARMS["b"]["um"] ** 2 / (ink.sum() * ARMS["a"]["um"] ** 2))
    donors_b.append({"ink": ink_b, "neg": neg_b, "resid": resid_b, "msoft": to_b(donors[-1]["msoft"], True),
                     "rstd": k_den_b})
    RESULTS["donors"][-1].update({"b_ink_px": int(ink_b.sum()), "b_ink_area_ratio_physical": round(area_b, 4),
                                  "b_ink_and_background_apart": not bool((ink_b & neg_b).any()),
                                  "b_resid_rstd": k_den_b, "b_sheet_layer": sheet_b,
                                  "b_ink_contrast_by_layer_in_texture_sd": [round(p, 3) for p in prof_b],
                                  "b_ink_contrast_at_sheet": round(prof_b[sheet_b], 3)})
    oy_b, ox_b = (int(round(554.0 + (o - 511.5) / R_B)) for o in (oy, ox))   # the core's start in the 1109 px window
    write_job(f"b_{name}", np.clip(np.rint(to_b(box, True, 1109)), 0, 255).astype(np.uint8), ARMS["b"]["um"])
    SCORE[f"b_{name}"] = (to_b(pos_w, False, 1109), to_b(neg_w, False, 1109), (oy_b, ox_b, ARMS["b"]["core"]))
    RESULTS["jobs"][f"b_{name}"] = {"kind": "scale_reference", "arm": "b", "seg": d["seg"], "donor": i,
                                    "reference": name}
    log(f"donor {i}: ink contrast at the sheet {prof[d['sheet_layer']]:.3f} at 9.362 um, {prof_b[sheet_b]:.3f} at "
        f"8.64 um (layer {sheet_b}); ink area at 8.64 / 9.362 um {area_b:.4f}; scale reference b_{name} written")
save()
log(f"{len(donors)} donors read; references and scale references written")
'''),
# 6. the targets, per arm: day 3's jobs in a function of the arm, then each whole surface of each arm
(r'''targets = W3["targets"][:LIMIT_TARGETS] if LIMIT_TARGETS else W3["targets"]
L28 = W3["layers28_from_render_planes"]


def read_render(sid, box):
    y0, y1, x0, x1 = box
    return np.asarray(RENDERS[sid][L28[0]:L28[1], y0:y1, x0:x1])


for t in targets:
    dn = donors[t["donor"]]
    sh = W3["shams"][t["sham"]]
    v = read_render(t["surface"], t["box"])
    cy0, cx0 = core_offset(t)
    core = v[:, cy0:cy0 + CORE, cx0:cx0 + CORE].astype(np.float32)
    core_resid = core - background(core, np.ones((CORE, CORE), bool))
    t_rstd = rstd(core_resid[LAYERS[0]:LAYERS[1]])
    k = t_rstd / dn["rstd"]
    t_resid = core - background(core, dn["neg"])                      # the swap replaces this
    r_d = dn["resid"]                                                 # surface to surface: no depth shift (amendment 1)
    sv = read_render(sh["surface"], sh["core"]).astype(np.float32)
    for rec, vol in ((t, core), (sh, sv)):                            # the renders are the ones the pick read
        prof = ndimage.uniform_filter1d(vol.reshape(vol.shape[0], -1).mean(1).astype(np.float32), 3)
        if max(abs(round(float(a_), 1) - b_) for a_, b_ in zip(prof, rec["profile"])) > 0.051:
            RESULTS["status"] = f"failed: the render under {rec.get('name', rec['surface'])} {rec['core']} has changed"
            save()
            raise SystemExit(RESULTS["status"])
    sham_r = sv - background(sv, dn["neg"])
    k_sham = t_rstd / rstd(sham_r[LAYERS[0]:LAYERS[1]][:, dn["neg"]])
    xs = W["shams"][t["sham"]]                                        # day 1's PHerc0139 blank sham, same index
    xv = read_box(xs["prefix"], xs["core"]).astype(np.float32)
    xsham_r = xv - background(xv, dn["neg"])                          # PHerc0139 texture, no ink, no depth shift
    k_x = t_rstd / rstd(xsham_r[LAYERS[0]:LAYERS[1]][:, dn["neg"]])
    pos = np.zeros(v.shape[1:], bool)
    neg = np.zeros(v.shape[1:], bool)
    pos[cy0:cy0 + CORE, cx0:cx0 + CORE], neg[cy0:cy0 + CORE, cx0:cx0 + CORE] = dn["ink"], dn["neg"]
    meta = {"surface": t["surface"], "donor": t["donor"], "sham_core": sh["core"], "sham_surface": sh["surface"],
            "k": k, "k_sham": k_sham, "xsham_seg": xs["seg"], "xsham_core": xs["core"], "k_xsham": k_x, "depth_shift": 0}
    name = f"{t['name']}__clean"
    write_job(name, v)
    SCORE[name] = (pos, neg, (cy0, cx0))
    RESULTS["jobs"][name] = dict(meta, kind="clean", strength=0.0)
    for mode in PLANTS:
        for s_ in STRENGTHS:
            name = f"{t['name']}__{mode}__s{s_:g}"
            vol, clipped = plant(v, r_d, s_, k, cy0, cx0, dn["msoft"], mode, t_resid)
            write_job(name, vol)
            SCORE[name] = (pos, neg, (cy0, cx0))
            RESULTS["jobs"][name] = dict(meta, kind="planted", plant=mode, strength=s_, clipped_share=clipped)
            name = f"{t['name']}__{mode}__sham{s_:g}"
            vol, clipped = plant(v, sham_r, s_, k_sham, cy0, cx0, dn["msoft"], mode, t_resid)
            write_job(name, vol)
            SCORE[name] = (pos, neg, (cy0, cx0))
            RESULTS["jobs"][name] = dict(meta, kind="sham", plant=mode, strength=s_, clipped_share=clipped)
            name = f"{t['name']}__{mode}__xsham{s_:g}"
            vol, clipped = plant(v, xsham_r, s_, k_x, cy0, cx0, dn["msoft"], mode, t_resid)
            write_job(name, vol)
            SCORE[name] = (pos, neg, (cy0, cx0))
            RESULTS["jobs"][name] = dict(meta, kind="xsham", plant=mode, strength=s_, clipped_share=clipped)
    log(f"{t['name']}: donor {t['donor']}, k {k:.3f}, sham k {k_sham:.3f}, PHerc0139 sham k {k_x:.3f}, surface to surface")
for sid in sorted(RENDERS):                                           # the models' own output on each whole surface
    write_job(f"whole_{sid}", np.asarray(RENDERS[sid][L28[0]:L28[1]]))
    RESULTS["jobs"][f"whole_{sid}"] = {"kind": "whole", "surface": sid}
save()
''', r'''targets = W4["targets"][:LIMIT_TARGETS] if LIMIT_TARGETS else W4["targets"]
L28 = W4["layers28_from_render_planes"]
DONORS = {"a": donors, "b": donors_b}


def read_render(arm, sid, box):
    y0, y1, x0, x1 = box
    return np.asarray(RENDERS[arm][sid][L28[0]:L28[1], y0:y1, x0:x1])


def target_jobs(arm, t, xs, xsham_r):
    """Day 3's jobs for one target in one arm (amendment 3). Arm A: the 9.362 um renders at core and box, as day 3.
    Arm B: the 8.64 um renders at core_b and box_b, 554 px cores, sigma 52 px, the donor's arrays at 8.64 um. xsham_r,
    the PHerc0139 sham residual, comes already in this arm's frame."""
    CORE, sigma, sfx = ARMS[arm]["core"], ARMS[arm]["sigma"], {"a": "", "b": "_b"}[arm]   # this arm's core and sigma
    dn = DONORS[arm][t["donor"]]
    sh = W4["shams"][t["sham"]]
    v = read_render(arm, t["surface"], t["box" + sfx])
    cy0, cx0 = core_offset(t, sfx)
    core = v[:, cy0:cy0 + CORE, cx0:cx0 + CORE].astype(np.float32)
    core_resid = core - background(core, np.ones((CORE, CORE), bool), sigma)
    t_rstd = rstd(core_resid[LAYERS[0]:LAYERS[1]])
    k = t_rstd / dn["rstd"]
    t_resid = core - background(core, dn["neg"], sigma)               # the swap replaces this
    r_d = dn["resid"]                                                 # surface to surface: no depth shift (amendment 1)
    su = read_render(arm, sh["surface"], sh["core" + sfx])
    for rec, vol in ((t, v[:, cy0:cy0 + CORE, cx0:cx0 + CORE]), (sh, su)):   # the renders are the ones the pick read,
        prof = ndimage.uniform_filter1d(vol.reshape(vol.shape[0], -1).mean(1).astype(np.float32), 3)   # read as it did
        if max(abs(round(float(a_), 1) - b_) for a_, b_ in zip(prof, rec["profile" + sfx])) > 0.051:
            RESULTS["status"] = (f"failed: the arm-{arm} render under {rec.get('name', rec['surface'])} "
                                 f"{rec['core' + sfx]} has changed")
            save()
            raise SystemExit(RESULTS["status"])
    sv = su.astype(np.float32)
    sham_r = sv - background(sv, dn["neg"], sigma)
    k_sham = t_rstd / rstd(sham_r[LAYERS[0]:LAYERS[1]][:, dn["neg"]])
    k_x = t_rstd / rstd(xsham_r[LAYERS[0]:LAYERS[1]][:, dn["neg"]])
    pos = np.zeros(v.shape[1:], bool)
    neg = np.zeros(v.shape[1:], bool)
    pos[cy0:cy0 + CORE, cx0:cx0 + CORE], neg[cy0:cy0 + CORE, cx0:cx0 + CORE] = dn["ink"], dn["neg"]
    meta = {"arm": arm, "surface": t["surface"], "donor": t["donor"], "sham_core": sh["core" + sfx],
            "sham_surface": sh["surface"], "k": k, "k_sham": k_sham, "xsham_seg": xs["seg"], "xsham_core": xs["core"],
            "k_xsham": k_x, "depth_shift": 0}
    name = f"{arm}_{t['name']}__clean"
    write_job(name, v, ARMS[arm]["um"])
    SCORE[name] = (pos, neg, (cy0, cx0, CORE))
    RESULTS["jobs"][name] = dict(meta, kind="clean", strength=0.0)
    for mode in PLANTS:
        for s_ in STRENGTHS:
            name = f"{arm}_{t['name']}__{mode}__s{s_:g}"
            vol, clipped = plant(v, r_d, s_, k, cy0, cx0, dn["msoft"], mode, t_resid)
            write_job(name, vol, ARMS[arm]["um"])
            SCORE[name] = (pos, neg, (cy0, cx0, CORE))
            RESULTS["jobs"][name] = dict(meta, kind="planted", plant=mode, strength=s_, clipped_share=clipped)
            name = f"{arm}_{t['name']}__{mode}__sham{s_:g}"
            vol, clipped = plant(v, sham_r, s_, k_sham, cy0, cx0, dn["msoft"], mode, t_resid)
            write_job(name, vol, ARMS[arm]["um"])
            SCORE[name] = (pos, neg, (cy0, cx0, CORE))
            RESULTS["jobs"][name] = dict(meta, kind="sham", plant=mode, strength=s_, clipped_share=clipped)
            name = f"{arm}_{t['name']}__{mode}__xsham{s_:g}"
            vol, clipped = plant(v, xsham_r, s_, k_x, cy0, cx0, dn["msoft"], mode, t_resid)
            write_job(name, vol, ARMS[arm]["um"])
            SCORE[name] = (pos, neg, (cy0, cx0, CORE))
            RESULTS["jobs"][name] = dict(meta, kind="xsham", plant=mode, strength=s_, clipped_share=clipped)
    log(f"{arm}_{t['name']}: donor {t['donor']}, k {k:.3f}, sham k {k_sham:.3f}, PHerc0139 sham k {k_x:.3f}, "
        f"surface to surface")


for t in targets:
    xs = W["shams"][t["sham"]]                                        # day 1's PHerc0139 blank sham, same index
    xv = read_box(xs["prefix"], xs["core"]).astype(np.float32)
    xsham_r = xv - background(xv, donors[t["donor"]]["neg"])          # PHerc0139 texture, no ink, no depth shift
    target_jobs("a", t, xs, xsham_r)
    target_jobs("b", t, xs, to_b(xsham_r, True))                      # arm B: the same residual at 8.64 um
for arm in ARMS:                                                      # the models' own output on each whole surface
    for sid in (sorted(RENDERS[arm])[:LIMIT_WHOLE] if LIMIT_WHOLE else sorted(RENDERS[arm])):
        write_job(f"whole_{arm}_{sid}", np.asarray(RENDERS[arm][sid][L28[0]:L28[1]]), ARMS[arm]["um"])
        RESULTS["jobs"][f"whole_{arm}_{sid}"] = {"kind": "whole", "surface": sid, "arm": arm}
save()
'''),
# 7. scoring: the raw map kept for each job's own core (512 px in arm A, 554 px in arm B)
(r'''    for name, (pos, neg, (oy, ox)) in SCORE.items():
''', r'''    for name, (pos, neg, (oy, ox, core_px)) in SCORE.items():
'''),
(r'''            maps[f"{name}__{d}"] = np.rint(p[oy:oy + CORE, ox:ox + CORE] * 255).astype(np.uint8)   # the raw map, kept
''', r'''            maps[f"{name}__{d}"] = np.rint(p[oy:oy + core_px, ox:ox + core_px] * 255).astype(np.uint8)   # the raw map, kept
'''),
# 7b. completeness per arm: each arm is read when its own jobs and the shared control are scored in both directions,
# and the scale references when theirs are, so a missing score in one arm does not stop the other
(r'''RESULTS["complete"] = complete
''', r'''RESULTS["complete"] = complete
PART = {"a": [n for n in SCORED if J[n].get("arm") in ("a", None) and J[n]["kind"] != "scale_reference"],
        "b": [n for n in SCORED if J[n].get("arm") in ("b", None) and J[n]["kind"] != "scale_reference"],
        "scale": [n for n in SCORED if J[n]["kind"] in ("scale_reference", "reference")]}
complete_part = {p_: {tag: all(("forward" in J[n].get("auc", {}).get(tag, {}) and "reverse" in J[n]["auc"][tag])
                               for n in names) for tag in ck_paths} for p_, names in PART.items()}
RESULTS["complete_by_part"] = complete_part
'''),
# 8. the readout: day 3's for each arm (the control shared), then the difference and the scale references
(r'''# ---------------------------------------------------------------- 7. the day-3 readout (PREREG amendment 1)
''', r'''# ---------------------------------------------------------------- 7. the day-4 readout (PREREG amendment 3): day 3's per arm
'''),
(r'''readout, lines = {}, ["| checkpoint | dir | control (largest reference change) | clean | " +
''', r'''readout, lines = {}, ["| arm | checkpoint | dir | control (largest reference change) | clean | " +
'''),
(r'''                      "|---|---|---|---|" + "---|" * len(STRENGTHS) + "---|---|---|---|---|"]
for tag in ck_paths:
    if not complete[tag]:
        lines.append(f"| {tag} | INCOMPLETE: some jobs have no score; nothing is read |")
''', r'''                      "|---|---|---|---|---|" + "---|" * len(STRENGTHS) + "---|---|---|---|---|"]
for ARM, tag in [(a_, t_) for a_ in ("a", "b") for t_ in ck_paths]:     # amendment 3: arm A (primary), then arm B
    J = {n: j for n, j in RESULTS["jobs"].items() if j.get("arm") in (ARM, None)}   # this arm's jobs and the control
    if not complete_part[ARM][tag]:
        lines.append(f"| {ARM} | {tag} | INCOMPLETE: some of this arm's jobs have no score; this arm is not read |")
'''),
(r'''    readout[tag] = {"primary_direction": primary, "control_largest_reference_change": moved, "control_ok": control,
                    "curve": curve, "shams": shams, "sham_interquartile": sham_iqr, "xshams": xshams,
                    "xsham_interquartile": xsham_iqr, "checks_ok": checks,
                    "detection_floor": det, "clear_floor": clr, "read": bool(control and checks)}
''', r'''    readout.setdefault(ARM, {})[tag] = {"primary_direction": primary, "control_largest_reference_change": moved,
                                        "control_ok": control, "curve": curve, "shams": shams,
                                        "sham_interquartile": sham_iqr, "xshams": xshams,
                                        "xsham_interquartile": xsham_iqr, "checks_ok": checks,
                                        "detection_floor": det, "clear_floor": clr, "read": bool(control and checks)}
'''),
(r'''    lines.append(f"| {tag} | {primary} | {moved:.4f} ({'ok' if control else 'MOVED: not read'}) | {clean:.3f} | " +
''', r'''    lines.append(f"| {ARM} | {tag} | {primary} | {moved:.4f} ({'ok' if control else 'MOVED: not read'}) | {clean:.3f} | " +
'''),
(r'''RESULTS["readout"] = readout
open(f"{OUT}/summary.md", "w").write("\n".join(lines) + "\n")
''', r'''J = RESULTS["jobs"]                                                   # every job again
RESULTS["readout"] = readout
difference, scale_refs = {}, {}                                       # amendment 3: both descriptive, no threshold
lines += ["", "| arm A minus arm B, median over targets | dir | " + " | ".join(f"s = {s:g}" for s in [0.0] + STRENGTHS) +
          " | targets |", "|---|---|" + "---|" * (len(STRENGTHS) + 2)]
for tag in ck_paths:                                                  # for each checkpoint read in both arms
    ra, rb = readout.get("a", {}).get(tag), readout.get("b", {}).get(tag)
    if not (ra and rb and ra["read"] and rb["read"]):
        difference[tag] = {"read": False, "read_a": bool(ra and ra["read"]), "read_b": bool(rb and rb["read"])}
        lines.append(f"| {tag} | not read in both arms (A {'read' if ra and ra['read'] else 'not read'}, B "
                     f"{'read' if rb and rb['read'] else 'not read'}): no difference |")
        continue
    d_ = ra["primary_direction"]
    by_t = {}                                                         # target -> {s: arm A AUC minus arm B AUC}
    for n in J:
        if J[n].get("arm") == "a" and J[n]["kind"] in ("clean", "planted"):
            by_t.setdefault(n[2:].split("__")[0], {})[J[n]["strength"]] = (J[n]["auc"][tag][d_] -
                                                                          J["b" + n[1:]]["auc"][tag][d_])
    mid = {s_: med([v_[s_] for v_ in by_t.values()]) for s_ in [0.0] + STRENGTHS}
    difference[tag] = {"read": True, "primary_direction": d_, "median_a_minus_b": mid, "a_minus_b_by_target": by_t}
    lines.append(f"| {tag} | {d_} | " + " | ".join(f"{mid[s_]:+.3f}" for s_ in [0.0] + STRENGTHS) + f" | {len(by_t)} |")
lines += ["", "| scale references (arm B; not a gate) | dir | median AUC at 9.362 um | median AUC at 8.64 um | "
          "median A minus B |", "|---|---|---|---|---|"]
for tag in ck_paths:
    if not complete_part["scale"][tag]:
        lines.append(f"| {tag} | INCOMPLETE: the scale references are not read |")
        continue
    d_ = DAY1["gates"][f"{tag}/swap"]["primary_direction"]
    by_r = {n: {"auc_a": J[J[n]["reference"]]["auc"][tag][d_], "auc_b": J[n]["auc"][tag][d_]}
            for n in J if J[n]["kind"] == "scale_reference"}
    for v_ in by_r.values():
        v_["a_minus_b"] = v_["auc_a"] - v_["auc_b"]
    scale_refs[tag] = dict({f"median_{f_}": med([v_[f_] for v_ in by_r.values()]) for f_ in ("auc_a", "auc_b", "a_minus_b")},
                           primary_direction=d_, by_reference=by_r)
    lines.append(f"| {tag} | {d_} | {scale_refs[tag]['median_auc_a']:.3f} | {scale_refs[tag]['median_auc_b']:.3f} | "
                 f"{scale_refs[tag]['median_a_minus_b']:+.3f} |")
RESULTS["difference"], RESULTS["scale_references"] = difference, scale_refs
open(f"{OUT}/summary.md", "w").write("\n".join(lines) + "\n")
'''),
]
out = SRC
for old, new in REPS:
    if out.count(old) != 1:
        raise SystemExit(f"no single match for: {old[:80]!r}")
    out = out.replace(old, new)
for gone in ("W3", "windows_day3", "pherc0846b", "PHerc0846B", "d3t"):          # no day-3 input survives
    if gone in out:
        raise SystemExit(f"floor_day4.py still holds {gone!r}")
if "--check" in sys.argv[1:]:
    same = os.path.isfile(f"{HERE}/floor_day4.py") and open(f"{HERE}/floor_day4.py").read() == out
    print(f"floor_day4.py {'is' if same else 'is NOT'} what make_day4.py generates from floor_day3.py")
    sys.exit(0 if same else 1)
open(f"{HERE}/floor_day4.py", "w").write(out)
changed = [l for l in difflib.unified_diff(SRC.splitlines(), out.splitlines(), lineterm="", n=0)
           if l[:1] in "+-" and not l.startswith(("+++", "---"))]
print(f"floor_day4.py: {len(changed)} changed lines against floor_day3.py "
      f"({sum(1 for l in changed if l[0] == '-')} removed, {sum(1 for l in changed if l[0] == '+')} added); "
      f"sha256 {hashlib.sha256(out.encode()).hexdigest()}")
